<?php
define('POST_CONFIG', 'post_config');
define('POST_DATA', 'post_data');

include 'post.routing.php';
include 'post.function.php';
include 'post.hook.php';

if ( is_post_page() ) {
    add_css('/module/post/css/post.base.css');
    add_css('/module/post/css/post.layout.css');
    add_css('/module/post/css/post.css');
}
if ( is_post_config_page() ) {
    add_css('/module/post/css/post.config.css');
}
