<?php
$location = [];
$location['Metro Manila'] = [
    'Entire Metro Manila',
    'Caloocan',
    'Las Pinas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Paranaque',
    'Pasay',
    'Pasig',
    'Pateros',
    'Quezon',
    'San Juan',
    'Taguig',
    'Valenzuela',
];
$location['Abra'] = [
    'Entire Abra',
    'Bangued',
    'Boliney',
    'Bucay',
    'Bucloc',
    'Daguioman',
    'Danglas',
    'Dolores',
    'La Paz',
    'Lacub',
    'Lagangilang',
    'Lagayan',
    'Langiden',
    'Licuan-Baay',
    'Luba',
    'Malibcong',
    'Manabo',
    'Penarrubia',
    'Pidigan',
    'Pilar',
    'Sallapadan',
    'San Isidro',
    'San Juan',
    'San Quintin',
    'Tayum',
    'Tineg',
    'Tubo',
    'Villaviciosa',
];
$location['Agusan del Norte'] = [
    'Entire Agusan del Norte',
    'Buenavista',
    'Butuan',
    'Cabadbaran',
    'Carmen',
    'Jabonga',
    'Kitcharao',
    'Las Nieves',
    'Magallanes',
    'Nasipit',
    'Remedios T. Romualdez',
    'Santiago',
    'Tubay',
];
$location['Agusan del Sur'] = [
    'Entire Agusan del Sur',
    'Bayugan',
    'Bunawan',
    'Esperanza',
    'La Paz',
    'Loreto',
    'Prosperidad',
    'Rosario',
    'San Francisco',
    'San Luis',
    'Santa Josefa',
    'Sibagat',
    'Talacogon',
    'Trento',
    'Veruela',
];
$location['Aklan'] = [
    'Entire Aklan',
    'Altavas',
    'Balete',
    'Banga',
    'Batan',
    'Burungan',
    'Ibajay',
    'Kalibo',
    'Lezo',
    'Libacao',
    'Madalag',
    'Makato',
    'Malay',
    'Malinao',
    'Nabas',
    'New Washington',
    'Numancia',
    'Tangalan',
];
$location['Albay'] = [
    'Entire Albay',
    'Bacacay',
    'Camalig',
    'Daraga',
    'Guinobatan',
    'Jovellar',
    'Legazpi',
    'Libon',
    'Ligao',
    'Malilipot',
    'Malinao',
    'Manito',
    'Oas',
    'Pio Duran',
    'Polangui',
    'Rapu-Rapu',
    'Santo Domingo',
    'Tabaco',
    'Tiwi',
];
$location['Antique'] = [
    'Entire Antique',
    'Anini-y',
    'Barbaza',
    'Belison',
    'Bugasong',
    'Caluya',
    'Culasi',
    'Hamtic',
    'Laua-An',
    'Libertad',
    'Pandan',
    'Patnongon',
    'San Jose',
    'San Remigio',
    'Sebaste',
    'Sibalom',
    'Tibiao',
    'Tobias Fornier (Dao)',
    'Valderrama',
];
$location['Apayao'] = [
    'Entire Apayao',
    'Calanasan (Bayag)',
    'Conner',
    'Flora',
    'Kabugao',
    'Luna',
    'Pudtol',
    'Santa Marcela',
];
$location['Aurora'] = [
    'Entire Aurora',
    'Baler',
    'Casiguran',
    'Dilasag',
    'Dinalungan',
    'Dingalan',
    'Dipaculao',
    'Maria Aurora',
    'San Luis',
];
$location['Basilan'] = [
    'Entire Basilan',
    'Akbar',
    'Al-Barka',
    'Hadji Mohammad Ajul',
    'Isabela',
    'Lamitan',
    'Lantawan',
    'Maluso',
    'Sumisip',
    'Tipo-Tipo',
    'Tuburan',
    'Ungkaya Pukan',
];
$location['Bataan'] = [
    'Entire Bataan',
    'Abucay',
    'Bagac',
    'Balanga',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
];
$location['Batanes'] = [
    'Entire Batanes',
    'Basco',
    'Itbayat',
    'Ivana',
    'Mahatao',
    'Sabtang',
    'Uyugan',
];
$location['Batangas'] = [
    'Entire Batangas',
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Batangas',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lipa',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataas Na Kahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Santo Tomas',
    'Taal',
    'Talisay',
    'Tanauan',
    'Taysan',
    'Tingloy',
    'Tuy',
];
$location['Benguet'] = [
    'Entire Benguet',
    'Atok',
    'Baguio',
    'Bakun',
    'Bokod',
    'Buguias',
    'Itogon',
    'Kabayan',
    'Kapangan',
    'Kibungan',
    'La Trinidad',
    'Mankayan',
    'Sablan',
    'Tuba',
    'Tublay',
];
$location['Biliran'] = [
    'Entire Biliran',
    'Almeria',
    'Biliran',
    'Cabucgayan',
    'Caibiran',
    'Culaba',
    'Kawayan',
    'Maripipi',
    'Naval',
];
$location['Bohol'] = [
    'Entire Bohol',
    'Albuquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Balilihan',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Getafe (Jetafe)',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'Pres. Carlos P. Garcia (Pitogo)',
    'Sagbayan (Borja)',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Tagbilaran',
    'Talibon',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
];
$location['Bukidnon'] = [
    'Entire Bukidnon',
    'Baungon',
    'Cabanglasan',
    'Damulog',
    'Dangcagan',
    'Don Carlos',
    'Impasug-Ong',
    'Kadingilan',
    'Kalilangan',
    'Kibawe',
    'Kitaotao',
    'Lantapan',
    'Libona',
    'Malaybalay',
    'Malitbog',
    'Manolo Fortich',
    'Maramag',
    'Pangantucan',
    'Quezon',
    'San Fernando',
    'Sumilao',
    'Talakag',
    'Valencia',
];
$location['Bulacan'] = [
    'Entire Bulacan',
    'Angat',
    'Balagtas (Bigaa)',
    'Baliuag',
    'Bocaue',
    'Bulacan',
    'Bustos',
    'Calumpit',
    'Dona Remedios Trinidad',
    'Guiguinto',
    'Hagonoy',
    'Malolos',
    'Marilao',
    'Meycauayan',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Jose Del Monte',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
];
$location['Cagayan'] = [
    'Entire Cagayan',
    'Abulug',
    'Alcala',
    'Allacapan',
    'Amulung',
    'Aparri',
    'Baggao',
    'Ballesteros',
    'Buguey',
    'Calayan',
    'Camalaniugan',
    'Claveria',
    'Enrile',
    'Gattaran',
    'Gonzaga',
    'Iguig',
    'Lal-Lo',
    'Lasam',
    'Pamplona',
    'Penablanca',
    'Piat',
    'Rizal',
    'Sanchez-Mira',
    'Santa Ana',
    'Santa Praxedes',
    'Santa Teresita',
    'Santo Nino (Faire)',
    'Solana',
    'Tuao',
    'Tuguegarao',
];
$location['Camarines Norte'] = [
    'Entire Camarines Norte',
    'Basud',
    'Capalonga',
    'Daet',
    'Jose Panganiban',
    'Labo',
    'Mercedes',
    'Paracale',
    'San Lorenzo Ruiz (Imelda)',
    'San Vicente',
    'Santa Elena',
    'Talisay',
    'Vinzons',
];
$location['Camarines Sur'] = [
    'Entire Camarines Sur',
    'Baao',
    'Balatan',
    'Bato',
    'Bombon',
    'Buhi',
    'Bula',
    'Cabusao',
    'Calabanga',
    'Camaligan',
    'Canaman',
    'Caramoan',
    'Del Gallego',
    'Gainza',
    'Goa',
    'Iriga',
    'Lagonoy',
    'Libmanan',
    'Lupi',
    'Magarao',
    'Milaor',
    'Minalabac',
    'Nabua',
    'Naga',
    'Ocampo',
    'Pamplona',
    'Pasacao',
    'Pili',
    'Presentacion (Parubcan)',
    'Ragay',
    'Sagnay',
    'San Fernando',
    'San Jose',
    'Sipocot',
    'Siruma',
    'Tigaon',
    'Tinambac',
];
$location['Camiguin'] = [
    'Entire Camiguin',
    'Catarman',
    'Guinsiliban',
    'Mahinog',
    'Mambajao',
    'Sagay',
];
$location['Capiz'] = [
    'Entire Capiz',
    'Cuartero',
    'Dao',
    'Dumalag',
    'Dumarao',
    'Ivisan',
    'Jamindan',
    'Ma-Ayon',
    'Mambusao',
    'Panay',
    'Panitan',
    'Pilar',
    'Pontevedra',
    'President Roxas',
    'Roxas',
    'Sapi-An',
    'Sigma',
    'Tapaz',
];
$location['Catanduanes'] = [
    'Entire Catanduanes',
    'Bagamanoc',
    'Baras',
    'Bato',
    'Caramoran',
    'Gigmoto',
    'Pandan',
    'Panganiban (Payo)',
    'San Andres (Calolbon)',
    'San Miguel',
    'Viga',
    'Virac',
];
$location['Cavite'] = [
    'Entire Cavite',
    'Alfonso',
    'Amadeo',
    'Bacoor',
    'Carmona',
    'Cavite',
    'Dasmarinas',
    'Gen. Mariano Alvarez',
    'Gen. Emilio Aguinaldo',
    'Gen. Trias',
    'Imus',
    'Indang',
    'Kawit',
    'Magallanes',
    'Maragondon',
    'Mendez (Mendez-Nunez)',
    'Naic',
    'Noveleta',
    'Rosario',
    'Silang',
    'Tagaytay',
    'Tanza',
    'Ternate',
    'Trece Martires',
];
$location['Cebu'] = [
    'Entire Cebu',
    'Alcantara',
    'Alcoy',
    'Alegria',
    'Aloguinsa',
    'Argao',
    'Asturias',
    'Badian',
    'Balamban',
    'Bantayan',
    'Barili',
    'Bogo',
    'Boljoon',
    'Borbon',
    'Carcar',
    'Carmen',
    'Catmon',
    'Cebu',
    'Compostela',
    'Consolacion',
    'Cordova',
    'Daanbantayan',
    'Dalaguete',
    'Danao',
    'Dumanjug',
    'Ginatilan',
    'Lapu-Lapu',
    'Liloan',
    'Madridejos',
    'Malabuyoc',
    'Mandaue',
    'Medellin',
    'Minglanilla',
    'Moalboal',
    'Naga',
    'Oslob',
    'Pilar',
    'Pinamungahan',
    'Poro',
    'Ronda',
    'Samboan',
    'San Fernando',
    'San Francisco',
    'San Remigio',
    'Santa Fe',
    'Santander',
    'Sibonga',
    'Sogod',
    'Tabogon',
    'Tabuelan',
    'Talisay',
    'Toledo',
    'Tuburan',
    'Tudela',
];
$location['Compostela Valley'] = [
    'Entire Compostela Valley',
    'Compostela',
    'Laak (San Vicente)',
    'Mabini (Dona Alicia)',
    'Maco',
    'Maragusan (San Mariano)',
    'Mawab',
    'Monkayo',
    'Montevista',
    'Nabunturan',
    'New Bataan',
    'Pantukan',
];
$location['Cotabato'] = [
    'Entire Cotabato',
    'Alamada',
    'Aleosan',
    'Antipas',
    'Arakan',
    'Banisilan',
    'Carmen',
    'Kabacan',
    'Kidapawan',
    'Libungan',
    'Magpet',
    'Makilala',
    'Matalam',
    'Midsayap',
    'M\Lang',
    'Pigkawayan',
    'Pikit',
    'President Roxas',
    'Tulunan',
];
$location['Davao del Norte'] = [
    'Entire Davao del Norte',
    'Asuncion (Saug)',
    'Braulio E. Dujali',
    'Carmen',
    'Kapalong',
    'New Corella',
    'Panabo',
    'Samal Island Garden',
    'San Isidro',
    'Santo Tomas',
    'Tagum',
    'Talaingod',
];
$location['Davao del Sur'] = [
    'Entire Davao del Sur',
    'Bansalan',
    'Davao',
    'Digos',
    'Don Marcelino',
    'Hagonoy',
    'Jose Abad Santos (Trinidad)',
    'Kiblawan',
    'Magsaysay',
    'Malalag',
    'Malita',
    'Matanao',
    'Padada',
    'Santa Cruz',
    'Santa Maria',
    'Sarangani',
    'Sulop',
];
$location['Davao Oriental'] = [
    'Entire Davao Oriental',
    'Baganga',
    'Banaybanay',
    'Boston',
    'Caraga',
    'Cateel',
    'Governor Geneloso',
    'Lupon',
    'Manay',
    'Mati',
    'San Isidro',
    'Tarragona',
];
$location['Dinagat Islands'] = [
    'Entire Dinagat Islands',
    'Basilisa (Rizal)',
    'Cagdianao',
    'Dinagat',
    'Libjo (Abjor)',
    'Loreto',
    'San Jose',
    'Tubajon',
];
$location['Eastern Samar'] = [
    'Entire Eastern Samar',
    'Arteche',
    'Balangiga',
    'Balangkayan',
    'Borongan',
    'Can-Avid',
    'Dolores',
    'General MacArthur',
    'Giporlos',
    'Guiuan',
    'Hernani',
    'Jipapad',
    'Lawaan',
    'Llorente',
    'Maslog',
    'Maydolong',
    'Mercedes',
    'Oras',
    'Quinapondan',
    'Salcedo',
    'San Julian',
    'San Policarpo',
    'Sulat',
    'Taft',
];
$location['Guimaras'] = [
    'Entire Guimaras',
    'Buenavista',
    'Jordan',
    'Nueva Valencia',
    'San Lorenzo',
    'Sibunag',
];
$location['Ifugao'] = [
    'Entire Ifugao',
    'Aguinaldo',
    'Alfonso Lista (Potia)',
    'Asipulo',
    'Banaue',
    'Hingyon',
    'Hungduan',
    'Kiangan',
    'Lagawe',
    'Lamut',
    'Mayoyao',
    'Tinoc',
];
$location['Ilocos Norte'] = [
    'Entire Ilocos Norte',
    'Adams',
    'Bacarra',
    'Badoc',
    'Bangui',
    'Banna (Espiritu)',
    'Batac',
    'Burgos',
    'Carasi',
    'Currimao',
    'Dingras',
    'Dumalneg',
    'Laoag',
    'Marcos',
    'Nueva Era',
    'Pagudpud',
    'Paoay',
    'Pasuquin',
    'Piddig',
    'Pinili',
    'San Nicolas',
    'Sarrat',
    'Solsona',
    'Vintar',
];
$location['Ilocos Sur'] = [
    'Entire Ilocos Sur',
    'Alilem',
    'Banayoyo',
    'Bantay',
    'Burgos',
    'Cabugao',
    'Candon',
    'Caoayan',
    'Cervantes',
    'Galimuyod',
    'Gregorio Del Pilar (Concepcion)',
    'Lidlidda',
    'Magsingal',
    'Nagbukel',
    'Narvacan',
    'Quirino (Angkaki)',
    'Salcedo (Baugen)',
    'San Emilio',
    'San Esteban',
    'San Ildefonso',
    'San Juan (Lapog)',
    'San Vicente',
    'Santa',
    'Santa Catalina',
    'Santa Cruz',
    'Santa Lucia',
    'Santa Maria',
    'Santiago',
    'Santo Domingo',
    'Sigay',
    'Sinait',
    'Sugpon',
    'Suyo',
    'Tagudin',
    'Vigan',
];
$location['Iloilo'] = [
    'Entire Iloilo',
    'Ajuy',
    'Alimodian',
    'Anilao',
    'Badiangan',
    'Balasan',
    'Banate',
    'Barotac Nuevo',
    'Barotac Viejo',
    'Batad',
    'Bingawan',
    'Cabatuan',
    'Calinog',
    'Carles',
    'Concepcion',
    'Dingle',
    'Duenas',
    'Dumangas',
    'Estancia',
    'Guimbal',
    'Igbaras',
    'Iloilo',
    'Janiuay',
    'Lambunao',
    'Leganes',
    'Lemery',
    'Leon',
    'Maasin',
    'Miagao',
    'Mina',
    'New Lucena',
    'Oton',
    'Passi',
    'Pavia',
    'Pototan',
    'San Dionisio',
    'San Enrique',
    'San Joaquin',
    'San Miguel',
    'San Rafael',
    'Santa Barbara',
    'Sara',
    'Tigbauan',
    'Tubungan',
    'Zarraga',
];
$location['Isabela'] = [
    'Entire Isabela',
    'Alicia',
    'Angadanan',
    'Aurora',
    'Benito Soliven',
    'Burgos',
    'Cabagan',
    'Cabatuan',
    'Cauayan',
    'Cordon',
    'Delfin Albano (Magsaysay)',
    'Dinapigue',
    'Divilican',
    'Echague',
    'Gamu',
    'Ilagan',
    'Jones',
    'Luna',
    'Maconacon',
    'Mallig',
    'Naguilian',
    'Palanan',
    'Quezon',
    'Quirino',
    'Ramon',
    'Reina Mercedes',
    'Roxas',
    'San Agustin',
    'San Guillermo',
    'San Isidro',
    'San Manuel',
    'San Mariano',
    'San Mateo',
    'San Pablo',
    'Santa Maria',
    'Santiago',
    'Santo Tomas',
    'Tumauini',
];
$location['Kalinga'] = [
    'Entire Kalinga',
    'Balbalan',
    'Lubuagan',
    'Pasil',
    'Pinukpuk',
    'Rizal (Liwan)',
    'Tabuk',
    'Tanudan',
    'Tinglayan',
];
$location['La Union'] = [
    'Entire La Union',
    'Agoo',
    'Aringay',
    'Bacnotan',
    'Bagulin',
    'Balaoan',
    'Bangar',
    'Bauang',
    'Burgos',
    'Caba',
    'Luna',
    'Naguilian',
    'Pugo',
    'Rosario',
    'San Fernando',
    'San Gabriel',
    'San Juan',
    'Santo Tomas',
    'Santol',
    'Sudipen',
    'Tubao',
];
$location['Laguna'] = [
    'Entire Laguna',
    'Alaminos',
    'Bay',
    'Binan',
    'Cabuyao',
    'Calamba',
    'Calauan',
    'Cavinti',
    'Famy',
    'Kalayaan',
    'Liliw',
    'Los Banos',
    'Luisiana',
    'Lumban',
    'Mabitac',
    'Magdalena',
    'Majayjay',
    'Nagcarlan',
    'Paete',
    'Pagsanjan',
    'Pakil',
    'Pangil',
    'Pila',
    'Rizal',
    'San Pablo',
    'San Pedro',
    'Santa Cruz',
    'Santa Maria',
    'Santa Rosa',
    'Siniloan',
    'Victoria',
];
$location['Lanao del Norte'] = [
    'Entire Lanao del Norte',
    'Bacolod',
    'Baloi',
    'Baroy',
    'Iligan',
    'Kapatagan',
    'Kauswagan',
    'Kolambugan',
    'Lala',
    'Linamon',
    'Magsaysay',
    'Maigo',
    'Matungao',
    'Munai',
    'Nunungan',
    'Pantao Ragat',
    'Pantar',
    'Poona Piagapo',
    'Salvador',
    'Sapad',
    'Sultan Naga Dimaporo (Karomatan)',
    'Tagoloan',
    'Tangcal',
    'Tubod',
];
$location['Lanao del Sur'] = [
    'Entire Lanao del Sur',
    'Bacolod-Kalawi (Bacolod-Grande)',
    'Balabagan',
    'Balindong (Watu)',
    'Bayang',
    'Binidayan',
    'Buadiposo-Buntong',
    'Bubong',
    'Bumbaran',
    'Butig',
    'Calanogas',
    'Ditsaan-Ramain',
    'Ganassi',
    'Kapai',
    'Kapatagan',
    'Lumba-Bayabao (Maguing)',
    'Lumbaca-Unayan',
    'Lumbatan',
    'Lumbayanague',
    'Madalum',
    'Madamba',
    'Maguing',
    'Malabang',
    'Marantao',
    'Marawi',
    'Marogong',
    'Masiu',
    'Mulondo',
    'Pagayawan (Tatarikan)',
    'Piagapo',
    'Picong (Sultan Gumander)',
    'Poona Bayabao (Gata)',
    'Pualas',
    'Saguiaran',
    'Sultan Dumalondong',
    'Tagoloan li',
    'Tamparan',
    'Taraka',
    'Tubaran',
    'Tugaya',
    'Wao',
];
$location['Leyte'] = [
    'Entire Leyte',
    'Abuyog',
    'Alangalang',
    'Albuera',
    'Babatngon',
    'Barugo',
    'Bato',
    'Baybay',
    'Burauen',
    'Calubian',
    'Capoocan',
    'Carigara',
    'Dagami',
    'Dulag',
    'Hilongos',
    'Hindang',
    'Inopacan',
    'Isabel',
    'Jaro',
    'Javier (Bugho)',
    'Julita',
    'Kananga',
    'La Paz',
    'Leyte',
    'MacArthur',
    'Mahaplag',
    'Matag-Ob',
    'Matalom',
    'Mayorga',
    'Merida',
    'Ormoc',
    'Palo',
    'Palompon',
    'Pastrana',
    'San Isidro',
    'San Miguel',
    'Santa Fe',
    'Tabango',
    'Tabontabon',
    'Tacloban',
    'Tanauan',
    'Tolosa',
    'Tunga',
    'Villaba',
];
$location['Maguindanao'] = [
    'Entire Maguindanao',
    'Ampatuan',
    'Barira',
    'Buldon',
    'Buluan',
    'Datu Abdullah Sangki',
    'Datu Anggal Midtimbang',
    'Datu Blah T. Sinsuat',
    'Datu Odin Sinsuat (Dinaig)',
    'Datu Paglas',
    'Datu Piang',
    'Datu Saudi-Ampatuan',
    'Datu Unsay',
    'Gen. S. K. Pendatun',
    'Guindulungan',
    'Kabuntalan (Tumbao)',
    'Mamasapano',
    'Mangudadatu',
    'Matanog',
    'Northern Kabuntalan',
    'Pagagawan',
    'Pagalungan',
    'Paglat',
    'Pandag',
    'Parang',
    'Rajah Buayan',
    'Shariff Aguak (Maganoy)',
    'South Upi',
    'Sultan Kudarat (Nuling)',
    'Sultan Mastura',
    'Sultan sa Barongis',
    'Talayan',
    'Talitay',
    'Upi',
];
$location['Marinduque'] = [
    'Entire Marinduque',
    'Boac',
    'Buenavista',
    'Gasan',
    'Mogpog',
    'Santa Cruz',
    'Torrijos',
];
$location['Masbate'] = [
    'Entire Masbate',
    'Aroroy',
    'Baleno',
    'Balud',
    'Batuan',
    'Cataingan',
    'Cawayan',
    'Claveria',
    'Dimasalang',
    'Esperanza',
    'Mandaon',
    'Masbate',
    'Milagros',
    'Mobo',
    'Monreal',
    'Palanas',
    'Pio V. Corpuz (Limbuhan)',
    'Placer',
    'San Fernando',
    'San Jacinto',
    'San Pascual',
    'Uson',
];
$location['Misamis Occidental'] = [
    'Entire Misamis Occidental',
    'Aloran',
    'Baliangao',
    'Bonifacio',
    'Calamba',
    'Clarin',
    'Concepcion',
    'Don Victoriano Chiongbian',
    'Jimenez',
    'Lopez Jaena',
    'Oroquieta',
    'Ozamis',
    'Panaon',
    'Plaridel',
    'Sapang Dalaga',
    'Sinacaban',
    'Tangub',
    'Tudela',
];
$location['Misamis Oriental'] = [
    'Entire Misamis Oriental',
    'Alubijid',
    'Balingasag',
    'Balingoan',
    'Binuangan',
    'Cagayan De Oro',
    'Claveria',
    'El Salvador',
    'Gingoog',
    'Gitagum',
    'Initao',
    'Jasaan',
    'Kinoguitan',
    'Lagonglong',
    'Laguindingan',
    'Libertad',
    'Lugait',
    'Magsaysay (Linugos)',
    'Manticao',
    'Medina',
    'Naawan',
    'Opol',
    'Salay',
    'Sugbongcogon',
    'Tagoloan',
    'Talisayan',
    'Villanueva',
];
$location['Mountain Province'] = [
    'Entire Mountain Province',
    'Barlig',
    'Bauko',
    'Besao',
    'Bontoc',
    'Natonin',
    'Paracelis',
    'Sabangan',
    'Sadanga',
    'Sagada',
    'Tadian',
];
$location['Negros Occidental'] = [
    'Entire Negros Occidental',
    'Bacolod',
    'Bago',
    'Binalbagan',
    'Cadiz',
    'Calatrava',
    'Candoni',
    'Cauayan',
    'Enrique B. Magalona (Saravia)',
    'Escalante',
    'Himamaylan',
    'Hinigaran',
    'Hinoba-An (Asia)',
    'Ilog',
    'Isabela',
    'Kabankalan',
    'La Carlota',
    'La Castellana',
    'Manapla',
    'Moises Padilla (Magallon)',
    'Murcia',
    'Pontevedra',
    'Pulupandan',
    'Sagay',
    'Salvador Benedicto',
    'San Carlos',
    'San Enrique',
    'Silay',
    'Talisay',
    'Toboso',
    'Valladolid',
    'Victorias',
];
$location['Negros Oriental'] = [
    'Entire Negros Oriental',
    'Amlan (Ayuquitan)',
    'Ayugon',
    'Bacong',
    'Bais',
    'Basay',
    'Bayawan  (Tulong)',
    'Bindoy (Payabon)',
    'Canlaon',
    'Dauin',
    'Dumaguete',
    'Guihulngan',
    'Jimalalud',
    'La Libertad',
    'Mabinay',
    'Manjuyod',
    'Pamplona',
    'San Jose',
    'Santa Catalina',
    'Siaton',
    'Sibulan',
    'Tayasan',
    'Tanjay',
    'Valencia (Luzurrizga)',
    'Vallehermoso',
    'Zamboanguita',
];
$location['Northern Samar'] = [
    'Entire Northern Samar',
    'Allen',
    'Biri',
    'Bobon',
    'Capul',
    'Catarman',
    'Catubig',
    'Gamay',
    'Laoang',
    'Lapinig',
    'Las Navas',
    'Lavezares',
    'Lope De Vega',
    'Mapanas',
    'Mondragon',
    'Palapag',
    'Pambujan',
    'Rosario',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Roque',
    'San Vicente',
    'Silvino Lobos',
    'Victoria',
];
$location['Nueva Ecija'] = [
    'Entire Nueva Ecija',
    'Aliaga',
    'Bongabon',
    'Cabanatuan',
    'Cabiao',
    'Caranglan',
    'Cuyapo',
    'Gabaldon (Bitulok and Sarabani)',
    'Gapan',
    'General Mamerto Natividad',
    'General Tinio (Payapa)',
    'Guimba',
    'Jaen',
    'Laur',
    'Licab',
    'Llanera',
    'Lupao',
    'Munoz',
    'Nampicuan',
    'Palayan',
    'Pantabangan',
    'Penaranda',
    'Quezon',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Leonardo',
    'Santa Rosa',
    'Santo Domingo',
    'Talavera',
    'Talugtug',
    'Zaragoza',
];
$location['Nueva Vizcaya'] = [
    'Entire Nueva Vizcaya',
    'Alfonso Castaneda',
    'Ambaguio',
    'Aritao',
    'Bagabag',
    'Bambang',
    'Bayombong',
    'Diadi',
    'Dupax Del Norte',
    'Dupax Del Sur',
    'Kasibu',
    'Kayapa',
    'Quezon',
    'Santa Fe',
    'Solano',
    'Villaverde',
];
$location['Occidental Mindoro'] = [
    'Entire Occidental Mindoro',
    'Abra de Ilog',
    'Calintaan',
    'Looc',
    'Lubang',
    'Magsaysay',
    'Mamburao',
    'Paluan',
    'Rizal',
    'Sablayan',
    'San Jose',
    'Santa Cruz',
];
$location['Oriental Mindoro'] = [
    'Entire Oriental Mindoro',
    'Baco',
    'Bansud',
    'Bongabong',
    'Bulalacao (San Pedro)',
    'Calapan',
    'Gloria',
    'Mansalay',
    'Naujan',
    'Pinamalayan',
    'Pola',
    'Puerto Galera',
    'Roxas',
    'San Teodoro',
    'Socorro',
    'Victoria',
];
$location['Palawan'] = [
    'Entire Palawan',
    'Aborlan',
    'Agutaya',
    'Araceli',
    'Balabac',
    'Bataraza',
    'Brooke\s Point',
    'Busuanga',
    'Cagayancillo',
    'Coron',
    'Culion',
    'Cuyo',
    'Dumaran',
    'El Nido (Bacuit)',
    'Kalayaan',
    'Linapacan',
    'Magsaysay',
    'Narra',
    'Puerto Princesa',
    'Quezon',
    'Rizal (Marcos)',
    'Roxas',
    'San Vicente',
    'Sofronio Espanola',
    'Taytay',
];
$location['Pampanga'] = [
    'Entire Pampanga',
    'Angeles',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Fernando',
    'San Luis',
    'San Simon',
    'Santa Ana',
    'Santa Rita',
    'Santo Tomas',
    'Sasmoan',
];
$location['Pangasinan'] = [
    'Entire Pangasinan',
    'Agno',
    'Aguilar',
    'Alaminos',
    'Alcala',
    'Anda',
    'Asingan',
    'Balungao',
    'Bani',
    'Basista',
    'Bautista',
    'Bayambang',
    'Binalonan',
    'Binmaley',
    'Bolinao',
    'Bugallon',
    'Burgos',
    'Calasiao',
    'Dagupan',
    'Dasol',
    'Infanta',
    'Labrador',
    'Laoac',
    'Lingayen',
    'Mabini',
    'Malasiqui',
    'Manaoag',
    'Mangaldan',
    'Mangatarem',
    'Mapandan',
    'Natividad',
    'Pozorrubio',
    'Rosales',
    'San Carlos',
    'San Fabian',
    'San Jacinto',
    'San Manuel',
    'San Nicolas',
    'San Quintin',
    'Santa Barbara',
    'Santa Maria',
    'Santo Tomas',
    'Sison',
    'Sual',
    'Tayug',
    'Umingan',
    'Urbiztondo',
    'Urdaneta',
    'Villasis',
];
$location['Quezon'] = [
    'Entire Quezon',
    'Agdangan',
    'Alabat',
    'Atimonan',
    'Buenavista',
    'Burdeos',
    'Calauag',
    'Candelaria',
    'Catanauan',
    'Dolores',
    'General Luna',
    'General Nakar',
    'Guinayangan',
    'Gumaca',
    'Infanta',
    'Jomalig',
    'Lopez',
    'Lucban',
    'Lucena',
    'Macalelon',
    'Mauban',
    'Mulanay',
    'Padre Burgos',
    'Pagbilao',
    'Panukulan',
    'Patnanungan',
    'Perez',
    'Pitogo',
    'Plaridel',
    'Polillo',
    'Quezon',
    'Real',
    'Sampaloc',
    'San Andres',
    'San Antonio',
    'San Francisco (Aurora)',
    'San Narciso',
    'Sariaya',
    'Tagkawayan',
    'Tayabas',
    'Tiaong',
    'Unisan',
];
$location['Quirino'] = [
    'Entire Quirino',
    'Aglipay',
    'Cabarroguis',
    'Diffun',
    'Maddela',
    'Nagtipunan',
    'Saguday',
];
$location['Rizal'] = [
    'Entire Rizal',
    'Angono',
    'Antipolo',
    'Baras',
    'Binangonan',
    'Cainta',
    'Cardona',
    'Jalajala',
    'Morong',
    'Pililla',
    'Rodriguez (Montalban)',
    'San Mateo',
    'Tanay',
    'Taytay',
    'Teresa',
];
$location['Romblon'] = [
    'Entire Romblon',
    'Alcantara',
    'Banton',
    'Cajidiocan',
    'Calatrava',
    'Concepcion',
    'Corcuera',
    'Ferrol',
    'Looc',
    'Magdiwang',
    'Odiongan',
    'Romblon',
    'San Agustin',
    'San Andres',
    'San Fernando',
    'San Jose',
    'Santa Fe',
    'Santa Maria (Imelda)',
];
$location['Samar'] = [
    'Entire Samar',
    'Almagro',
    'Basey',
    'Calbayog',
    'Calbiga',
    'Catbalogan',
    'Daram',
    'Gandara',
    'Hinabangan',
    'Jiabong',
    'Marabut',
    'Matuguinao',
    'Motiong',
    'Pagsanghan',
    'Paranas (Wright)',
    'Pinabacdao',
    'San Jorge',
    'San Jose De Buan',
    'San Sebastian',
    'Santa Margarita',
    'Santa Rita',
    'Santo Nino',
    'Tagapul-An',
    'Talalora',
    'Tarangan',
    'Villareal',
    'Zumarraga',
];
$location['Sarangani'] = [
    'Entire Sarangani',
    'Alabel',
    'Glan',
    'Kiamba',
    'Maasim',
    'Maitum',
    'Malapatan',
    'Malungon',
];
$location['Siquijor'] = [
    'Entire Siquijor',
    'Enrique Villanueva',
    'Larena',
    'Lazi',
    'Maria',
    'San Juan',
    'Siquijor',
];
$location['Sorsogon'] = [
    'Entire Sorsogon',
    'Barcelona',
    'Bulan',
    'Bulusan',
    'Casiguran',
    'Castilla',
    'Donsol',
    'Gubat',
    'Irosin',
    'Juban',
    'Magallanes',
    'Matnog',
    'Pilar',
    'Prieto Diaz',
    'Santa Magdalena',
    'Sorsogon',
];
$location['South Cotabato'] = [
    'Entire South Cotabato',
    'Banga',
    'General Santos  (Dadiangas)',
    'Koronadal',
    'Lake Sebu',
    'Norala',
    'Polomolok',
    'Santo Nino',
    'Surallah',
    'Tampakan',
    'Tantangan',
    'Tupi',
    'T\boli',
];
$location['Southern Leyte'] = [
    'Entire Southern Leyte',
    'Anahawan',
    'Bontoc',
    'Hinunangan',
    'Hinundayan',
    'Libagon',
    'Liloan',
    'Limasawa',
    'Maasin',
    'Macrohon',
    'Malitbog',
    'Padre Burgos',
    'Pintuyan',
    'Saint Bernard',
    'San Francisco',
    'San Juan (Cabalian)',
    'San Ricardo',
    'Silago',
    'Sogod',
    'Tomas Oppus',
];
$location['Sultan Kudarat'] = [
    'Entire Sultan Kudarat',
    'Bagumbayan',
    'Columbio',
    'Esperanza',
    'Isulan',
    'Kalamansig',
    'Lambayong (Mariano Marcos)',
    'Lebak',
    'Lutayan',
    'Palimbang',
    'President Quirino',
    'Sen. Ninoy Aquino',
    'Tacurong',
];
$location['Sulu'] = [
    'Entire Sulu',
    'Hadji Panglima Tahil (Marungga)',
    'Indanan',
    'Jolo',
    'Kalingalan Caluang',
    'Lugus',
    'Luuk',
    'Maimbung',
    'Old Panamao',
    'Pandami',
    'Panglima Estino (New Panamao)',
    'Pangutaran',
    'Parang',
    'Pata',
    'Patikul',
    'Siasi',
    'Talipao',
    'Tapul',
    'Tongkil',
];
$location['Surigao del Norte'] = [
    'Entire Surigao del Norte',
    'Alegria',
    'Bacuag',
    'Burgos',
    'Cagdianao',
    'Claver',
    'Dapa',
    'Del Carmen',
    'General Luna',
    'Gigaquit',
    'Mainit',
    'Malimono',
    'Pilar',
    'Placer',
    'San Benito',
    'San Francisco (Anao-Aon)',
    'San Isidro',
    'San Jose',
    'Santa Monica (Sapao)',
    'Sison',
    'Socorro',
    'Surigao  (Capital)',
    'Tagana-an',
    'Tubod',
];
$location['Surigao del Sur'] = [
    'Entire Surigao del Sur',
    'Barobo',
    'Bayabas',
    'Bislig',
    'Cagwait',
    'Cantilan',
    'Carmen',
    'Carrascal',
    'Cortes',
    'Hinatuan',
    'Lanuza',
    'Lianga',
    'Lingig',
    'Madrid',
    'Marihatag',
    'San Agustin',
    'San Miguel',
    'Tagbina',
    'Tago',
    'Tandag',
];
$location['Tarlac'] = [
    'Entire Tarlac',
    'Anao',
    'Bamban',
    'Camiling',
    'Capas',
    'Concepcion',
    'Gerona',
    'Lapaz',
    'Mayantoc',
    'Moncada',
    'Paniqui',
    'Pura',
    'Ramos',
    'San Clemente',
    'San Jose',
    'San Manuel',
    'Santa Ignacia',
    'Tarlac',
    'Victoria',
];
$location['Tawi-tawi'] = [
    'Entire Tawi-tawi',
    'Bongao',
    'Languyan',
    'Mapun (Cagayan De Tawi-Tawi)',
    'Panglima Sugala (Balimbing)',
    'Sapa-Sapa',
    'Simunul',
    'Sitangkai',
    'South Ubian',
    'Tandubas',
    'Turtle Islands',
];
$location['Zambales'] = [
    'Entire Zambales',
    'Botolan',
    'Cabangan',
    'Candelaria',
    'Castillejos',
    'Iba',
    'Masinloc',
    'Olongapo',
    'Palauig',
    'San Antonio',
    'San Felipe',
    'San Marcelino',
    'San Narciso',
    'Santa Cruz',
    'Subic',
];
$location['Zamboanga City'] = [
    'Entire Zamboanga',
];
$location['Zamboanga del Norte'] = [
    'Entire Zamboanga del Norte',
    'Bacungan (Leon T. Postigo)',
    'Baliguian',
    'Dapitan',
    'Dipolog',
    'Godod',
    'Gutalac',
    'Jose Dalman (Ponot)',
    'Kalawit',
    'Katipunan',
    'La Libertad',
    'Labason',
    'Liloy',
    'Manukan',
    'Mutia',
    'Pinan (New Pinan)',
    'Polanco',
    'Pres. Manuel A. Roxas',
    'Rizal',
    'Salug',
    'Sergio Osmena Sr.',
    'Siayan',
    'Sibuco',
    'Sibutad',
    'Sindangan',
    'Siocon',
    'Sirawai',
    'Tampilisan',
];
$location['Zamboanga del Sur'] = [
    'Entire Zamboanga del Sur',
    'Aurora',
    'Bayog',
    'Dimataling',
    'Dinas',
    'Dumalinao',
    'Dumingag',
    'Guipos',
    'Josefina',
    'Kumalarang',
    'Labangan',
    'Lakewood',
    'Lapuyan',
    'Mahayag',
    'Margosatubig',
    'Midsalip',
    'Molave',
    'Pagadian',
    'Pitogo',
    'Ramon Magsaysay (Liargo)',
    'San Miguel',
    'San Pablo',
    'Sominot (Don Mariano Marcos)',
    'Tabina',
    'Tambulig',
    'Tigbao',
    'Tukuran',
    'Vincenzo A. Sagun',
];
$location['Zamboanga Sibugay'] = [
    'Entire Zamboanga Sibugay',
    'Alicia',
    'Buug',
    'Diplahan',
    'Imelda',
    'Ipil',
    'Kabasalan',
    'Mabuhay',
    'Malangas',
    'Naga',
    'Olutanga',
    'Payao',
    'Roseller Lim',
    'Siay',
    'Talusan',
    'Titay',
    'Tungawan',
];
