<div class='temp-page schoolDormitory'>
	<div class='title'>School Dormitory</div>
	<div class='group kr-text'>
		<p style="margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed; text-align: center;"><span style="font-size: 14pt; font-family: '맑은 고딕'; color: #a54200; font-weight: bold;"><br></span></p>
		<p style="margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed; text-align: center;"><span style="font-size: 14pt; font-family: '맑은 고딕'; color: #a54200; font-weight: bold;">학원</span><span style="font-size: 14pt; font-family: '맑은 고딕'; color: #a54200; font-weight: bold;">&nbsp;</span><span style="font-size: 14pt; font-family: '맑은 고딕'; color: #a54200; font-weight: bold;">기숙사 소개</span></p>
		<p style="margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed;">&nbsp;</p>
		<p style="margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed;">&nbsp;</p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: red; font-weight: bold;"><span style="font-size: 14pt;">Multi-Language Power</span> </span><span style="color: #111111;">어학원은 학원과 기숙사가 함께 있어 기상부터 취침까지 편안함과 안정감을 제공하여 자연스러운 수업 분위기를 제공합니다</span><span style="color: #111111;">. </span><span style="color: #111111;">아이들의 스케줄 관리와 시설 및 환경을 관리 하는 </span><span style="color: #111111;">8</span><span style="color: #111111;">명의 스텝</span><span style="color: #111111;">, </span><span style="color: #111111;">그리고 한국인 부원장님께서 학원 내&nbsp; 기거하시며 근무를 하고 있어 아이들에게 최고의 수업과 교육환경을 부여하며</span><span style="color: #111111;">, 1</span><span style="color: #111111;">층엔 치과</span><span style="color: #111111;">, </span><span style="color: #111111;">내과 병원이 위치하고 있어 필요 시 신속한 조치가 가능합니다</span><span style="color: #111111;">.</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">&nbsp;</span></p>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><br></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 27 </span><span style="color: #111111;">개 맨투맨 룸</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 7 </span><span style="color: #111111;">개 </span><span style="color: #111111;">소그룹</span><span style="color: #111111;">스터디</span><span style="color: #111111;"> 룸</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 3</span><span style="color: #111111;">개 </span><span style="color: #111111;">Presentation, </span><span style="color: #111111;">시청각 교실</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 50</span><span style="color: #111111;">개 화상 영어 룸</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 농구</span><span style="color: #111111;">, </span><span style="color: #111111;">축구</span><span style="color: #111111;">, </span><span style="color: #111111;">배구</span><span style="color: #111111;">, </span><span style="color: #111111;">배드민턴 등 운동 공간</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 최소 </span><span style="color: #111111;">60</span><span style="color: #111111;">여명 수용 가능 기숙 시설</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> TV, DVD, English Books</span><span style="color: #111111;">를 통한 여가 시간 활용과 영어 능력 향상을 함께</span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #111111;"><br></span></span></div>
		<div class="O1" style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; margin-left: 0.5in; text-indent: -0.31in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">•<span style="color: #111111;"> 조리사가 제공하는 한식</span><span style="color: #111111;">, </span><span style="color: #111111;">중식</span><span style="color: #111111;">, </span><span style="color: #111111;">양식</span><span style="color: #111111;">, </span><span style="color: #111111;">필리핀 음식 등 다양한 식생활</span></span></div>
		<p style="margin-top: 0pt; margin-bottom: 0pt; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;">&nbsp;</span></p>
	</div>
</div>