<?php
use sap\src\Module;
use sap\src\Route;

if ( ! Module::enabled('app') ) {
    return;
}

Route::add('/app/front_page', 'app\\App\\frontPage');
Route::add('/app/offline', 'app\\App\\offline');
Route::add('/app/postList/*', 'app\\App\\postList');
Route::add('/app/login', 'app\\App\\login');
Route::add('/app/loginSubmit', 'app\\App\\loginSubmit');
Route::add('/app/post/comment/submit', 'app\\App\\postCommentSubmit');

header('Access-Control-Allow-Origin: *');
sys()->setConfig(URL_SITE, 'http://'.domain().'/');

