<?php
define('POST_CONFIG', 'post_config');
define('POST_DATA', 'post_data');
define('POST_VOTE_HISTORY', 'post_vote_history');




include 'post.routing.php';
include 'post.function.php';
include 'post.hook.php';

if ( is_post_page() ) {
    add_css('/core/module/post/css/post.base.css');
    add_css('/core/module/post/css/post.layout.css');
    add_css('/core/module/post/css/post.component.css');
}
if ( is_post_config_page() ) {
    add_css('/core/module/post/css/post.config.css');
}
