<div class='temp-page multiLanguage'>
	<div class='title kr-text'>Multi-Language Power 어학원 소개</div>
	<div class='group kr-text'>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed; text-align: center;"><span style="font-size: 14pt; font-family: 'times new roman', times;"><span style="color: #a54200; font-weight: bold;"><br></span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed; text-align: center;"><span style="font-size: 18pt; font-family: 'times new roman', times;"><span style="color: #a54200; font-weight: bold;">MLP </span><span style="color: #a54200; font-weight: bold;">소개</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed; text-align: center;"><span style="font-size: 14pt; font-family: 'times new roman', times;"><span style="color: #a54200; font-weight: bold;"><br></span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;">&nbsp;</p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: red; font-weight: bold;">멀티랭귀지파워</span><span style="color: red; font-weight: bold;">(MLP) </span><span style="color: red; font-weight: bold;">어학원</span><span style="color: #333333;">은 이미 온라인 영어시장에서 오랜 기간 터를 닦아온 어학원입니다.</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #333333;">2008년 필리핀에서 가장 안전하고 정, 재계 상위 층들의 주거 지역인 알라방에 설립 되어진 이래 중국, 일본에 이어 새롭게 한국시장 진출의 발판을 마련하고 있습니다. 현재 온라인 수강생은 일본 중국 학생만 200여명 이상이 등록해있으며, 새롭게 꾸민 현대식 시설에는 방음장치가 설치된 1:1강의실 27실, 그룹강의실 7실, 컨퍼런스룸3실, 시청각실, 휴게실 등이 갖춰져 있으며 4층, 3층 건물 2동 전체를 모두 사용하는 넓은 공간으로 타 학원에 비해 수강생이 안락함과 편안함을 느끼기에 충분합니다. </span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #333333;">석명문(石明文) 멀티랭귀지 어학원 이사장님 (필리핀계 대만인)은 이미 중국 현지와 일본 지역에 다양한 인적 네트워크를 확보하고 있어, 영어와 중국어의 동시 수강이 가능하며 중국어 강사는 모두 중국 현지에서 확보된 원어민 강사들입니다.</span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #333333;"><br></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="color: #333333;"><span style="font-size: 12pt; font-family: 'times new roman', times;">영어회화 ESL 및 IELTS, SAT, iBT TOFLE, TOEIC (미국, 영국 원어민교사진과16년여간TOFLE, TOIEC 전문 수석 강사이신 문형욱 교육 원장님이 직접 강의), HSK (중국어 공인 자격시험)에 독보적이고 전문적인 커리큘럼을 가지고 있으며, 또한 학생들에게 보다 넓은 시야를 제공하기 위해 필리핀 약 20여 개 대학을 비롯해&nbsp;</span><span style="font-family: 'times new roman', times; font-size: 12pt;">미국, 호주, 중국의 명문 대학들과의&nbsp;</span><span style="font-family: 'times new roman', times; font-size: 12pt; line-height: 150%; text-indent: 0.01in;">파트너쉽이 맺어져 있고,&nbsp;</span><span style="font-family: 'times new roman', times; font-size: 12pt;">호주연계연수유학, 중국 명문 대학 주최 “중국 언어, 문화, 관광 체험 캠프” 부문에서도&nbsp;</span><span style="font-family: 'times new roman', times; font-size: 12pt; line-height: 150%; text-indent: 0.01in;">멀티랭귀지어학원은 자체적인 네트워크를 확보하고 있읍니다. 현재 호주연계연수 대학으로 시드니대학교, 시드니 공과대학교, 센트럴퀸즈랜드대학교, 홈즈컬리지, STI컬리지 등과 협약을 맺고 학생들의 세계로의 진출에 밑받침이 되고 있습니다.</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #333333;"><br></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #333333;">무엇보다 멀티랭귀지어학원의 강점은 2년간의 연구기간을 거쳐 제작된 자체제작 교재입니다. 기존의 학생들이 옥스포드나STEP BY STEP등 통상적인 교재로만 공부를 해서 학생 수준과는 잘 맞지 않는 경우가 있습니다.&nbsp; 영어학습에는 교재가 가장 중요하기에 약 4년간의 화상영어 교육을 통한 자체 데이터 베이스를 기본으로 2년여에 걸쳐 교재개발에 심혈을 기울였습니다</span>. <span style="color: red; font-weight: bold;">Multi-Language Power</span><span style="color: #333333;">는 모든 학생들이 서로 자극이 되어 선의의 경쟁으로 학습의 효율성을 최대화 시킬 수 있게 하며, 독해력, 회화, 문법, 쓰기, 청취력 학습 등 다양하고 전문화된 교육을 통해 단순한 회화에만 국한되지 않고 영어로 된 다양한 정보 수집, 분석, 가공하여 report를 써내거나 토론이나 발표를 통해 단순한 의사소통을 떠나 자신의 생각까지 표현하는 실용적인 교육을 추구하고 있습니다.</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; color: #333333;"><br></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><span style="color: #333333;">조기유학, 장.단기 영어 연수, 영어캠프, 기업체 사원 스펙 쌓기 연수와 Team Building 등의 다방면에 걸쳐 가장 전문적이며 진정한 교육기관, 교육자로서의 역할이 바로 저희 MLP가 추구하는 비젼이며 이상이며우리 아이들이 자라 치열한 경쟁과 협력 속에 성공의 지름길로 나아갈 수 있는 가장 기본이 되는</span> <span style="color: red; font-weight: bold;">언어 능력</span><span style="color: #333333;">의 해결책을 제시해주는 것이 저희</span> <span style="color: red; font-weight: bold;">Multi-Language Power</span><span style="background-color: #ffffff; color: #333333;">의 교육 목표이자 이념입니다.</span></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; background-color: #ffffff; color: #333333;"><br></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times; background-color: #ffffff; color: #333333;">이제 이중언어 교육은 선택이 아닌 필수가 되고 있습니다. 영어뿐만 아니라 중국어 또한 필수 언어인 시대에 우리는 살고 있습니다. 새로운 다국어 어학센터 중심의 다양하고 전문화된 교육을 통해 멀티랭귀지 어학원은 미래의 전문 리더 양성에 심혈을 기울이고 있습니다.</span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><br></span></p>
		<p style="line-height: 150%; margin-top: 0pt; margin-bottom: 0pt; text-indent: 0.01in; direction: ltr; unicode-bidi: embed;"><span style="font-size: 12pt; font-family: 'times new roman', times;"><br></span></p>
	</div>
</div>