<div class='temp-page earlyCost clearfix'>
	<div class='title'>Study Abroad in Universities of USA, Australia And Philippines</div>
	<span style="margin: 0px; padding: 0px; font-size: 18pt; font-family: 'times new roman', times; color: #008080; font-weight: bold; margin-bottom: 10px; display: block;">USA</span>
	<div class='group'>		
		<img src='<?php echo $url_site ?>/theme/englishworld/img/priceUS.jpg'>
		<span style="font-family: 'times new roman',times; color: #008080; font-size: 18pt;"><span style="margin: 0px; padding: 0px; font-weight: bold;">Australia</span></span></p>
		<p style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif; font-size: 14pt;"><span style="margin: 0px; padding: 0px; color: red; font-weight: bold;"><br></span></span></p>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;">•</span><span style="margin: 0px; padding: 0px;">&nbsp; Central Queensland University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;">•</span><span style="margin: 0px; padding: 0px;">&nbsp; Holmes College</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;">•</span><span style="margin: 0px; padding: 0px;">&nbsp; Sydney Technology Institute</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;">•</span><span style="margin: 0px; padding: 0px;">&nbsp; University of Sydney</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;">•</span><span style="margin: 0px; padding: 0px;">&nbsp; University of Technology Sydney</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: 'times new roman',times; font-size: 14pt;"><span style="margin: 0px; padding: 0px;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; font-size: 12pt; font-family: arial,helvetica,sans-serif;">&nbsp;</span><span style="background-color: #f6f6f6; font-family: arial,helvetica,sans-serif; font-size: 13px;">&nbsp;</span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica, arial, sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline; text-align: justify;"><span style="color: #008080; font-size: 18pt; font-weight: bold; font-family: 'times new roman',times; text-indent: 0.15in;">Philippine</span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica, arial, sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline; text-align: justify;"><span style="color: #008080; font-size: 18pt; font-weight: bold; font-family: 'times new roman',times; text-indent: 0.15in;"><br></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; font-size: 12pt; font-family: arial,helvetica,sans-serif;"><span style="font-family: arial,helvetica,sans-serif; font-size: 16px; background-color: #f6f6f6;">• &nbsp;</span>De La Salle Manila</span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; font-size: 12pt; font-family: arial,helvetica,sans-serif;"><br></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">De La Salle&nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Dasmarinas</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Ateneo</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">&nbsp;de Manila University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">University of the Philippines</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Centro&nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Escolar</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">&nbsp;University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Our Lady Of Fatima University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Adamson University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Jose Rizal University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Mapua</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">&nbsp;Institute of Technology</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Technological University of the Philippines</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Philippine Normal University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Asia Pacific College</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Angeles University Foundation</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">College of the Holy Spirit</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Devry</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">&nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Unviersity</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">De La Salle&nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Araneta</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">&nbsp;University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Emilio Aguinaldo College</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Far Eastern University</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">University of the East</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;">• &nbsp;</span><span style="margin: 0px; padding: 0px; font-size: 12pt;">Our Lady of Fatima University&nbsp;</span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
		<div style="margin: 0pt 0px; padding: 0px; font-family: helvetica,arial,sans-serif; font-size: 13px; background-color: #f6f6f6; direction: ltr; unicode-bidi: embed; vertical-align: baseline;"><span style="font-family: arial,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; font-size: 12pt;"><br></span></span></div>
	</div>
</div>